---
apiVersion: v1 
kind: Pod
metadata:
  name: nodeName
  labels:
    name: web 
    env: dev
spec: 
  nodeName: "aks-nodepool1-42089134-vmss000002"
  containers:
  - name: web 
    image: nginx 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
