---
apiVersion: v1 
kind: Pod
metadata:
  name: web
  labels:
    name: web 
    env: dev
spec: 
  nodeSelector: 
    env: dev 
  containers:
  - name: web 
    image: nginx 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
