---
apiVersion: v1
kind: Pod 
metadata: 
  name: trial5
spec: 
  restartPolicy: OnFailure
  initContainers:
      - name: init1
        image: alpine
        args: 
          - sleep
          - 10s
  Containers: 
    - name: nginx
      image: nginx 