---
apiVersion: v1
kind: Pod 
metadata:
  name: trail4
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:its-jdk17
      resources:
      request:
        cpu: 500m
        memory: 256mi
      limits: 
        cpu: 1000m
        memory: 1gi
