---
apiVersion: v1
kind: Pod 
metadata: 
  - name: trial6
    labels:
       env: dev 
       app: nginx
       version: "1.0" 
spec: 
  containers:
    - name: nginx
      image: nginx 
      resources: 
        limits:
           cpu: 500m