---
apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: nginx-rs 
  labels: 
     purpose: understand 
spec: 
  minReadySeconds: 5 
  replicas: 3 
  selector: 
    matchLabel: 
      app: nginx
  template: 
    metadata:  
       labels: 
          app: nginx 
          version: v 1.0 
    spec:
      containers: 
        - name: nginx 
          image: nginx
          ports: 
            - containerPort: 80


---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports: 
    - targetPort: 80
      port: 80


   