---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: trail1-rs 
  label:
    name: trail1
spec: 
  minReadSecond: 10
  replicas: 3
  selector: 
    matchlables: 
      app: nginx
  template: 
  metadata: 
    labels: 
       apps: nginx
       env: dev
       version: "1.0" 
  spec: 
    containers: 
      - name: nginx 
        image: nginx
        resources: 
          limits: 
            cpu: 500m
            memory: 256mi
