---
 - name: activity 1
   become: yes
   hosts: all
   tasks: 
     - name: install apache2 server
       ansible.builtin.apt: 
         name: 
           - apache2
         state: present
         update_cache: yes