---
apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    name: toleration
spec: 
  tolerations: 
    - key: team
      operator: equal
      value: devops
      effort: noschedule
  containers:
  - name: toleration
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80