---
apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    name: toleration
spec:
  containers:
  - name: toleration
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80